name: CI/CD – Azure Deploy (Frontend: Static Web Apps, Backend: App Service)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  # Required: set these in GitHub repository Settings → Secrets and variables → Actions → Variables
  AZURE_RESOURCE_GROUP: mern-app-rg                   # Resource group containing the App Service
  AZURE_WEBAPP_BACKEND_NAME: your-backend-app-name    # Azure App Service (Linux) for backend
  NODE_VERSION: '18.x'

  # Frontend is deployed to Azure Static Web Apps (recommended for React SPA)
  # Set this in Secrets → Actions → Variables if you want to pin a specific SWA name/location (optional)
  # FRONTEND_APP_LOCATION: react-app
  # FRONTEND_OUTPUT_LOCATION: react-app/build

concurrency:
  group: azure-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend:
    name: Build & Deploy Frontend (Azure Static Web Apps)
    runs-on: ubuntu-latest
    outputs:
      frontend_url: ${{ steps.deploy.outputs.static_web_app_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install deps
        working-directory: react-app
        run: npm ci || npm i

      - name: Build React app
        working-directory: react-app
        run: npm run build
        env:
          # If your app needs build-time API URL, set it here or use .env.production
          CI: false

      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: react-app
          output_location: react-app/build

  backend:
    name: Build & Deploy Backend (Azure App Service)
    runs-on: ubuntu-latest
    needs: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install backend deps
        working-directory: node-app
        run: npm ci || npm i

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set backend app settings (MONGODB_URI, JWT_SECRET, FRONTEND_URL)
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config appsettings set \
              --resource-group "${{ env.AZURE_RESOURCE_GROUP }}" \
              --name "${{ env.AZURE_WEBAPP_BACKEND_NAME }}" \
              --settings \
                NODE_ENV=production \
                MONGODB_URI='${{ secrets.MONGODB_URI }}' \
                JWT_SECRET='${{ secrets.JWT_SECRET }}' \
                FRONTEND_URL='${{ needs.frontend.outputs.frontend_url }}'

      - name: Deploy to Azure Web App (Backend)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_BACKEND_NAME }}
          package: node-app
